---
title: "Plotly Bankruptcy"
author: "Kolton Bodnovich"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(tidyverse)
bank_1 <- read.csv('bank_01_07.csv')
bank_2 <- read.csv('bank_08_13.csv')
bank_3 <- read.csv('bank_14_18.csv')

bankruptcy <- rbind(bank_1, bank_2, bank_3)
```

```{r Map1_B2, echo = F}

#find count of asset cases by each state #includes Puerto Rico and Guam, does NOT include North Carolina and Alabama 

cases_by_state <- bankruptcy %>% 
  group_by(state) %>% 
  summarize(case_count = n(),
            category = case_when(
              case_count < 2000 ~ 'Under 2000', 
              case_count < 4999 ~ '2,000 - 4,999',
              case_count < 9999 ~ '5,000 - 9,999', 
              case_count >= 10000 ~ '10,000 OR MORE', 
              TRUE ~ 'NOT SERVED BY THE USTP'
            )) 


#create chloropleth of case count for each state 

cases_by_state %>% 
plot_geo(locationmode = 'USA-states') %>% 
  add_trace(z = ~case_count, 
            locations = ~state) %>% 
  layout(title = 'ASSET CASES BY STATE \n(TOTAL NUMBER CLOSED 2001-2018)', geo = list(scope = 'usa'))

```

```{r Alternative to B2, echo = F}
bankruptcy %>% 
  group_by(state) %>% 
  summarise(cases = n()) %>% 
  mutate(state = fct_reorder(state, cases)) %>% 
  plot_ly() %>% 
  add_markers(
    x = ~cases, y = ~state
  ) %>% 
  layout(xaxis = list(title = 'Asset Cases Closed 2001 - 2018'))

```


```{r DBELL, echo=FALSE}
library(readxl)
url <- "https://www.uscourts.gov/file/10864/download"
destfile <- "download.xls"
curl::curl_download(url, destfile)
filings_01 <- read_excel(destfile, range = "a7:f136")

library(openxlsx)

url_f2_18 <- "https://www.uscourts.gov/file/25503/download"
destfile_f2_18 <- "filings_18.xlsx"
filings_18 <- openxlsx::read.xlsx(url_f2_18,
                                  sheet = 1, 
                                  rows = 5:110,
                                  cols = 1:6,
                                  colNames = F)

filings_01 <-  na.omit(filings_01)

#change column names #2001

colnames(filings_01) <- c("state", "all_chap", "ch7", "ch11", "ch12", "ch3")

#remove rows that show circuit totals

filings_01 <- filings_01[c(-1,-3, -9, -16, -23, -33, -43, -53, -61, -72, -88, -97), ]

#modify column 1 by removing the district indicator #convert column1 to factors

filings_01$state <- factor(substr(filings_01$state, start = 1, stop = 2))

filings_01 <- filings_01 %>% 
  group_by(state) %>% 
  summarise(filings_2001 = sum(ch7, na.rm = T))

#remove rows that show circuit totals

filings_18 <- filings_18[c(-1,-3, -9, -16, -23, -33, -43, -53, -61, -71, -87, -96), ]

#change column names #2001

colnames(filings_18) <- c("state", "all_chap", "ch7", "ch11", "ch12", "ch3")

#modify column 1 by removing the district indicator #convert column1 to factors

filings_18$state <- factor(substr(filings_18$state, start =1, stop = 2))

#convert column 3 to numeric #2018

filings_18$ch7 <- as.numeric(filings_18$ch7)

filings_18 <- filings_18 %>% 
  group_by(state) %>% 
  summarise(filings_2018 = sum(ch7, na.rm = T))

ch7_filings <- left_join(filings_01, filings_18)

#plotly dumbbell chart

ch7_filings %>% 
  mutate(state = fct_reorder(state, filings_2001)) %>% 
  plot_ly() %>% 
  add_segments(
    x = ~filings_2018, y = ~state, 
    xend = ~filings_2001, yend = ~state, 
    color = I("gray"), showlegend = F
    ) %>% 
  add_markers(
    x = ~filings_2018, y = ~state, 
    color = I('blue'), 
    name = 'Filings in 2018') %>% 
  add_markers(
    x = ~filings_2001, y = ~state, 
    color = I('red'), 
    name = 'Filings in 2001') %>% 
  layout(xaxis = list(title = 'Chapter 7 Filings'))

```

```{r Fig B5, echo=FALSE}
bankruptcy %>% 
  group_by(state) %>% 
  summarise(total_assets = sum(total_gross_receipts)) %>% 
  mutate(State = fct_reorder(state, total_assets)) %>% 
  plot_ly() %>% 
  add_markers(
    x = ~total_assets, y = ~State
  ) %>% 
  layout(xaxis = list(title = 'Total Assets 2001 - 2018'))

```

